### ISSUE TITLE
메인

### ISSUE THREAD

**Issue by Jisu0528** [Jisu0528/SolutionChallenge_Front#1]
## Description
사이트의 메인 페이지이다.
마약 검색, 마약 뉴스 report, 의도치 않은 마약 복용 사례 기능을 포함한다.

## Todo
- [x] Header 구현 (#2)
- [x] 마약 검색 UI 구현
- [x] 마약 뉴스 Report UI 구현
- [x] 마약 복용 사례 리스트 UI 구현
- [x] Footer 구현 (#3)

## Etc
![image](https://github.com/Jisu0528/SolutionChallenge_Front/assets/71203375/c4a558c5-10cb-4f1d-b263-cd14987ba4bd)
